### PR TITLE
Deprecate REST API repo in favor of core repo

### PR DESCRIPTION
**Pull request by vedanshujain**
This deprecates the repo and ask the contributors to submit all issues and PRs directly in core repo. Once this is merged, we will start the process of transferring all issues and open PRs in the core repo.

### CODE REVIEW

**Review by ObliviousHarmony — COMMENTED** [review]
I have a few more suggestions:
- Set [abandoned: true](https://getcomposer.org/doc/04-schema.md#abandoned) in the `composer.json` and release it as-such
- Disable the creation of new issues entirely for this repository

**Review by claudiosanches — DISMISSED** [review]
Looks good. We need to also deprecated on packagist.org, let me know when we can do it.

**Comment by vedanshujain** [comment]
@ObliviousHarmony added the abandoned tag, will disable issues all the existing issues are migrated over to WooCommerce core repo. Right now disabling issues will hide all the issues.

**Review by ObliviousHarmony — APPROVED** [review]
Looks great!

**Review by claudiosanches — APPROVED** [review]

**Pull request merged**
