### PR TITLE
Query objects by created and modified

### PR DESCRIPTION
**Pull request by kepeder**
Added support for using `created_since`, `created_after`, `modified_since` and `modified_after` for all supported objects.

### CODE REVIEW

**Comment by weaselmetal** [comment]
Love it! First suggestion / question: would it be better to call the parameters `updated_after` and `created_after`?
And should one comparison be inclusive by convention (e.g. >= instead of >). If you get data up to date X and then after date X, you would miss an entry that was created exactly at X.

**Comment by kepeder** [comment]
I agree that the name `updated_after` and `created_after` in some ways is more descriptive; but WooCommerce already uses `since`, so that's why I used that key. But I'm open for changing it :-)
And about if one of the comparisons should be inclusive - open for it, but by making it strict less or more then; we can avoid fetching data more than necessary, which would be impossible by setting including :-)

**Comment by weaselmetal** [comment]
Those will be decisions that the WooCommerce team has to make.
For filtering by creation date, `after` is used as parameter name as per 
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders

**Comment by StaticVoidGabo** [comment]
any idea on when this will be available?

**Comment by exonity** [comment]
I need this feature, too.

**Comment by MioPedersen** [comment]
What is status for this? @claudiosanches

**Comment by claudiosanches** [comment]
@MioPedersen we don't have a schedule yet to release REST API v4, it will take some time yet, since requires documentation, testing all endpoints and so on.

**Comment by MioPedersen** [comment]
@claudiosanches Thanks for the response. Do you have any place where I can follow the release notes and potential announcements for new versions of the API?

**Comment by antoattanasio** [comment]
Could someone of the reviwers approve the request? This is a very needed function expecially for integration with third part software. Do someone know if there is a workaround?

**Comment by rrennick** [comment]
> Could someone of the reviwers approve the request?

@antoattanasio REST API development has been moved to https://github.com/woocommerce/woocommerce.

**Pull request closed without merging**
