### PR TITLE
Filtering products by date

### PR DESCRIPTION
**Pull request by kepeder**
Allow products and product variations to be queried by `updated_since`, `created_since`, `updated_before`, `created_before`

### CODE REVIEW

**Comment by MioPedersen** [comment]
Will this be part of v4 release?

**Comment by claudiosanches** [comment]
Thanks for your help, but we need to define this support for all other objects too.

**Review by claudiosanches — CHANGES_REQUESTED** [review]
Thanks for your help, but it need to be implemented for all objects.

**Comment by weaselmetal** [comment]
@claudiosanches please clarify which objects you mean exactly. I believe it's perfectly fine that different API endpoints offer different filter parameters, since the objects in question are different in nature and attributes.

**Comment by claudiosanches** [comment]
@weaselmetal all objects that returns `date_modified`, like products, variations, coupons, customers, orders, order notes, and refunds.

**Comment by weaselmetal** [comment]
Thanks for the response @claudiosanches. Is this the actual list or just an excerpt?
Do you oppose introducing the filter for orders and products only? If so, what's the reason?
Would this be the right way to add the filter parameters?
https://github.com/woocommerce/woocommerce-rest-api/pull/66/commits/8fa8d1fc96b34378ecca526a8054fcb38f26583f

**Comment by claudiosanches** [comment]
@weaselmetal 
>  Do you oppose introducing the filter for orders and products only? If so, what's the reason?

There's any reason to just implement in two endpoints? Once we implement in one every user will push to implement in the other endpoints, so it needs to be done in all endpoints at the same time, or we don't implement.

**Comment by weaselmetal** [comment]
> There's any reason to just implement in two endpoints?
For me, it's a yes. The most basic use case to integrate with the WooCommerce API is probably:
"In our own system, we want to see the new WooCommerce orders coming in."
If you do that, you don't want to have orders linger in open state forever. Therefore, you will want to learn about orders getting closed (being updated). And: you don't want your orders to refer to outdated product names or prices. Therefore, you'll probably want to know about changes on products. That basically describes everything I need to do for our integration, and reflects what users asked for in this and related issues.
Sure, once these exists, users might ask for the same filters on the resources you mentioned, but so far it doesn't seem to be the case. And I, as a programmer, am a strong supporter of the YAGNI (you aren't gonna need it) principle :). If no one asked for it, why would you do it?

**Comment by weaselmetal** [comment]
@kepeder - could you please share with us why you closed your PR? Are there any news on this matter? Thank you for your efforts.

**Comment by kepeder** [comment]
@weaselmetal it was merged into PR #124 :-)

**Comment by kepeder** [comment]
@weaselmetal If you really need it, you could clone that PR into the plugins folder and run composer install inside, you will have access to it in your WooCommerce after activating the plugin. Just note that all these features can change before it being merged :-)

**Pull request closed without merging**
